name: Build Linux

on:
  workflow_call:

env:
  BUILD_TESTS: ON
  BUILD_CCACHE: ON
  BUILD_PCH: ON
  CCACHE_DIR: ${{ github.workspace }}/.ccache
  CCACHE_BASEDIR: ${{ github.workspace }}
  CCACHE_MAXSIZE: 1G
  CCACHE_COMPILERCHECK: content
  CCACHE_SLOPPINESS: pch_defines,time_macros

jobs:
  archlinux:
    name: Arch Linux (${{ matrix.runner.arch }})
    runs-on: ${{ matrix.runner.os }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - { os: ubuntu-latest, arch: amd64 }
    container:
      image: archlinux:latest
    steps:
      - name: Install git and ca-certificates
        run: |
          pacman -Syu --noconfirm --needed ca-certificates git

      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Dependencies
        run: |
          ./ci/arch-depends.sh

      - name: Cache ccache
        if: env.BUILD_CCACHE == 'ON'
        uses: actions/cache@v6
        with:
          path: ${{ env.CCACHE_DIR }}
          key: linux-archlinux-${{ matrix.runner.arch }}-ccache-${{ github.sha }}
          restore-keys: |
            linux-archlinux-${{ matrix.runner.arch }}-ccache-

      - name: Build
        run: |
          ./ci/arch-build.sh

      - name: Run tests
        if: env.BUILD_TESTS == 'ON'
        run: |
          ./ci/tests.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: archlinux-${{ matrix.runner.arch }}
          path: arch
