name: Build

on:
  push:
    branches-ignore:
      - update-translations
    paths-ignore:
      - '*.md'
      - 'data/translations/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '*.md'
      - 'data/translations/**'
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write # needed for vcpkg cache and release upload

jobs:
  linux:
    name: Build Linux
    uses: ./.github/workflows/build-linux.yml
    secrets: inherit
